/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.JOptionPane;

/**
 *
 * @author gabii
 */
public class viewOperacion extends javax.swing.JFrame {

    /**
     * Creates new form viewOperacion
     */
    public viewOperacion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jb_limpiar = new javax.swing.JButton();
        jl_numero1 = new javax.swing.JLabel();
        jl_numero2 = new javax.swing.JLabel();
        jl_resultado = new javax.swing.JLabel();
        jb_suma = new javax.swing.JButton();
        jb_resta = new javax.swing.JButton();
        jb_multiplicacion = new javax.swing.JButton();
        jb_divicion = new javax.swing.JButton();
        jb_modulo = new javax.swing.JButton();
        jtf_numero1 = new javax.swing.JTextField();
        jtf_resultado = new javax.swing.JTextField();
        jtf_numero2 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jb_limpiar1 = new javax.swing.JButton();

        jb_limpiar.setBackground(new java.awt.Color(102, 102, 102));
        jb_limpiar.setText("Limpiar");
        jb_limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_limpiarActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jl_numero1.setFont(new java.awt.Font("Lucida Handwriting", 1, 12)); // NOI18N
        jl_numero1.setText("Número:");

        jl_numero2.setFont(new java.awt.Font("Lucida Handwriting", 1, 12)); // NOI18N
        jl_numero2.setText("Número:");

        jl_resultado.setFont(new java.awt.Font("Lucida Handwriting", 1, 12)); // NOI18N
        jl_resultado.setText("Resultado:");

        jb_suma.setBackground(new java.awt.Color(153, 153, 153));
        jb_suma.setFont(new java.awt.Font("Lucida Handwriting", 1, 12)); // NOI18N
        jb_suma.setText("Suma");
        jb_suma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_sumaActionPerformed(evt);
            }
        });

        jb_resta.setBackground(new java.awt.Color(153, 153, 153));
        jb_resta.setFont(new java.awt.Font("Lucida Handwriting", 1, 12)); // NOI18N
        jb_resta.setText("Resta");
        jb_resta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_restaActionPerformed(evt);
            }
        });

        jb_multiplicacion.setBackground(new java.awt.Color(153, 153, 153));
        jb_multiplicacion.setFont(new java.awt.Font("Lucida Handwriting", 1, 12)); // NOI18N
        jb_multiplicacion.setText("Multiplicacion");
        jb_multiplicacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_multiplicacionActionPerformed(evt);
            }
        });

        jb_divicion.setBackground(new java.awt.Color(153, 153, 153));
        jb_divicion.setFont(new java.awt.Font("Lucida Handwriting", 1, 12)); // NOI18N
        jb_divicion.setText("Divicion");
        jb_divicion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_divicionActionPerformed(evt);
            }
        });

        jb_modulo.setBackground(new java.awt.Color(153, 153, 153));
        jb_modulo.setFont(new java.awt.Font("Lucida Handwriting", 1, 12)); // NOI18N
        jb_modulo.setText("Modulo");
        jb_modulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_moduloActionPerformed(evt);
            }
        });

        jtf_numero1.setText(" ");

        jtf_resultado.setText(" ");

        jtf_numero2.setText(" ");

        jLabel1.setFont(new java.awt.Font("Lucida Handwriting", 1, 14)); // NOI18N
        jLabel1.setText("Calculadora De Botones MVC");

        jb_limpiar1.setBackground(new java.awt.Color(153, 153, 153));
        jb_limpiar1.setFont(new java.awt.Font("Lucida Handwriting", 1, 12)); // NOI18N
        jb_limpiar1.setText("Limpiar");
        jb_limpiar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_limpiar1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jb_divicion)
                                    .addComponent(jb_suma))
                                .addGap(47, 47, 47)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jb_resta, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jb_modulo, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(34, 34, 34)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jb_multiplicacion)
                                    .addComponent(jb_limpiar1)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jl_numero2)
                                        .addComponent(jl_numero1))
                                    .addComponent(jl_resultado))
                                .addGap(47, 47, 47)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtf_numero2, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtf_numero1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtf_resultado, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addComponent(jLabel1)))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_numero1)
                    .addComponent(jtf_numero1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_numero2)
                    .addComponent(jtf_numero2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_resultado)
                    .addComponent(jtf_resultado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jb_suma)
                    .addComponent(jb_resta)
                    .addComponent(jb_multiplicacion))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jb_modulo)
                    .addComponent(jb_divicion)
                    .addComponent(jb_limpiar1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jb_sumaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_sumaActionPerformed
         try {
            float numero1 = 0.0f;//variable numero1
            float numero2 = 0.0f;//variable numero2
            numero1 = Float.parseFloat(this.jtf_numero1.getText());//convierte el texto jtf a flotante y lo guarda en numero1
            numero2 = Float.parseFloat(this.jtf_numero2.getText());//convierte el texto jtf a flotante y lo guarda en numeri2
            float resultado = numero1 + numero2;
            this.jtf_resultado.setText(String.valueOf(resultado));
        }
        catch (NumberFormatException e){
            JOptionPane.showMessageDialog(this, "Numeros No Validos!");
        }
    }//GEN-LAST:event_jb_sumaActionPerformed

    private void jb_restaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_restaActionPerformed
         try { 
             float numero1 = 0.0f;
             float numero2 = 0.0f;
             numero1 = Float.parseFloat(this.jtf_numero1.getText());
             numero2 = Float.parseFloat(this.jtf_numero2.getText());
             float resultado = numero1 - numero2;
             this.jtf_resultado.setText(String.valueOf(resultado));
         }
         catch (NumberFormatException e){
             JOptionPane.showMessageDialog(this, "Numero No Valido!");
         }
    }//GEN-LAST:event_jb_restaActionPerformed

    private void jb_multiplicacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_multiplicacionActionPerformed
        try {
            float numero1 = 0.0f;
            float numero2 = 0.0f;
            numero1 = Float.parseFloat(this.jtf_numero1.getText());
            numero2 = Float.parseFloat(this.jtf_numero2.getText());
            float resultado = numero1 * numero2; 
            this.jtf_resultado.setText(String.valueOf(resultado));
        }
        catch (NumberFormatException e){
            JOptionPane.showMessageDialog(this, "NUMEROS NO VALIDOS!");
        }
    }//GEN-LAST:event_jb_multiplicacionActionPerformed

    private void jb_divicionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_divicionActionPerformed
        try {
            float numero1 = 0.0f;
            float numero2 = 0.0f;
            numero1 = Float.parseFloat(this.jtf_numero1.getText());
            numero2 = Float.parseFloat(this.jtf_numero2.getText());
            float resultado = numero1 / numero2; 
            this.jtf_resultado.setText(String.valueOf(resultado));
        }
        catch (NumberFormatException e){
            JOptionPane.showMessageDialog(this, "numero no valido");
        }
    }//GEN-LAST:event_jb_divicionActionPerformed

    private void jb_moduloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_moduloActionPerformed
         try {
             float numero1 = 0.0f;
             float numero2 = 0.0f;
             numero1 = Float.parseFloat(this.jtf_numero1.getText());
             numero2 = Float.parseFloat(this.jtf_numero2.getText());
             float resultado = numero1 % numero2; 
             this.jtf_resultado.setText(String.valueOf(resultado)); 
         }  
         catch (NumberFormatException e){
             JOptionPane.showMessageDialog(this, "el numero no es valido");
         }
    }//GEN-LAST:event_jb_moduloActionPerformed

    private void jb_limpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_limpiarActionPerformed
        this.jtf_numero1.setText("");
        this.jtf_numero2.setText("");
        this.jtf_resultado.setText("");
    }//GEN-LAST:event_jb_limpiarActionPerformed

    private void jb_limpiar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_limpiar1ActionPerformed
        this.jtf_numero1.setText("");
        this.jtf_numero2.setText("");
        this.jtf_resultado.setText("");
    }//GEN-LAST:event_jb_limpiar1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(viewOperacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(viewOperacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(viewOperacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(viewOperacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new viewOperacion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    public javax.swing.JButton jb_divicion;
    private javax.swing.JButton jb_limpiar;
    private javax.swing.JButton jb_limpiar1;
    public javax.swing.JButton jb_modulo;
    public javax.swing.JButton jb_multiplicacion;
    public javax.swing.JButton jb_resta;
    public javax.swing.JButton jb_suma;
    public javax.swing.JLabel jl_numero1;
    public javax.swing.JLabel jl_numero2;
    public javax.swing.JLabel jl_resultado;
    private javax.swing.JTextField jtf_numero1;
    public javax.swing.JTextField jtf_numero2;
    private javax.swing.JTextField jtf_resultado;
    // End of variables declaration//GEN-END:variables
}
